config/routes.rb
HackerClone::Application.routes.draw do
  root to: 'links#index'

  resources :links, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:new, :create, :index]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  validates :content, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments, as: :commentable
  validates :title, presence: true
  validates :content_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.create(comment_params)
    redirect_to link_path(@link)
  end

private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to links_path
    else
      render 'new'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to links_path
  end



private
  def link_params
    params.require(:link).permit(:title, :content_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div>
  <%= object.content %>
  <% if object.comments.any? %>
    <% object.comments.each do |comment| %>
      <%= render 'comment', object: comment %>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= render 'layouts/errors', object: @comment %>

<%= form_for [object, @comment] do |f| %>
  <div>
    <%= f.text_area :content %>
  </div>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/comments/_show.html.erb
<div>
  <%= object.content %>

  <% if object.comments.any? %>
    <% object.comments.each do |comment| %>
      <%= render 'show', object: comment %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'HackerClone' %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= render('layouts/errors', object: @link) %>

<%= form_for(@link) do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class='form-group'>
    <%= f.label :content_url %>
    <%= f.text_field :content_url %>
  </div>
  <%= f.submit(:class => 'btn btn-primary') %>
<% end %>

app/views/links/comments.html.erb
<h1><%= @link.title %></h1>

<%= render 'comments/form', object: @link %>

<% @link.comments.each do |comment| %>
  <%= render 'comments/show', object: comment %>
<% end %>

app/views/links/index.html.erb
<% content_for(:title, 'Links | HackerClone') %>
<%= link_to 'New link', new_link_path, :class => 'btn btn-default' %>
<h1>List of links</h1>

<ul>
  <% @links.each do |link| %>
    <li><a href='<%= link.content_url %>'><%= link.title %></a> |
      <%= link_to "#{link.comments.count} comments", link_path(link) %> |
      <%= link_to 'Delete', link_path(link), data: {confirm: 'You sure?', method: 'delete'}, :class => 'btn btn-danger' %></li>
  <% end %>
</ul>

app/views/links/new.html.erb
<% content_for(:title, 'New post | HackerClone') %>

<h1>New Post</h1>

<%= render 'form' %>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>

<%= render 'comments/form', object: @link %>

<% @link.comments.each do |comment| %>
  <%= render 'comments/comment', object: comment %>
<% end %>